import { useState } from "react"; 
import { Link,useLocation,useNavigate } from "react-router-dom"; import { ArrowRight, Eye, EyeOff, ShieldCheck, Sparkles, Store } from "lucide-react"; import Navbar from "../components/Navbar"; import { useAuth } from "../context/AuthContext";

export default function Login()
{const nav=useNavigate(),state=useLocation().state,{login}=useAuth();
const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[show,setShow]=useState(false),[error,setError]=useState(""),[loading,setLoading]=useState(false);
const submit=async e=>{e.preventDefault();setError("");setLoading(true);try{const user=await login(email,password);nav(`/${user.role}`)}catch(err){setError(err.message==="Failed to fetch"?"Cannot reach the server. Is the backend running?":err.message)}finally{setLoading(false)}};
return <><Navbar/><main className="page grid min-h-[82vh] items-center py-10 lg:grid-cols-[.9fr_1.1fr] lg:gap-16"><div className="hidden lg:block"><span className="inline-flex items-center gap-2 rounded-full bg-warm-50 px-3 py-1.5 text-xs font-bold text-warm-600">
    <Sparkles size={14}/> Welcome to Sakhi</span><h1 className="display mt-5 text-6xl leading-tight text-slate-950">Good businesses grow faster when communities know them.</h1><p className="mt-5 max-w-lg leading-7 text-slate-500">Sign in to shop local, manage your Sakhi business, or help move orders through the community.</p>
    <div className="mt-8 flex gap-5 text-sm font-semibold text-slate-500"><span className="flex items-center gap-2"><ShieldCheck size={17} className="text-sakhi-600"/> Verified identities</span><span className="flex items-center gap-2"><Store size={17} className="text-sakhi-600"/> Local marketplace</span></div></div>
    <form onSubmit={submit} className="card mx-auto w-full max-w-md p-7 sm:p-9"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-sakhi-600 text-white"><Sparkles size={20}/></span><h1 className="mt-5 text-2xl font-bold">Welcome back</h1><p className="mt-1 text-sm text-slate-500">Log in to your Sakhi account.</p>{state?.registered&&!error&&
    <div className="mt-4 rounded-xl bg-sakhi-50 p-3 text-sm text-sakhi-800">Account created successfully. Please log in.</div>}{error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<label className="mt-6 block text-sm font-bold">Email<input type="email" required className="input mt-2" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="mt-4 block text-sm font-bold">Password<div className="relative">
        <input type={show?"text":"password"} required className="input mt-2 pr-11" value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" aria-label="Toggle password visibility" onClick={()=>setShow(!show)} className="absolute right-3 top-1/2 translate-y-[-25%] text-slate-400">{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>
        <button disabled={loading} className="btn-primary mt-6 w-full">{loading?"Logging in...":"Login"}<ArrowRight size={16}/></button><div className="mt-5 rounded-xl bg-slate-50 p-3 text-center text-sm text-slate-600">New here? <Link to="/signup" className="font-bold text-sakhi-700">Create an account</Link><span className="mx-2 text-gray-300">·</span><Link to="/signup" className="font-bold text-sakhi-700">Join as delivery partner</Link></div></form></main></>}